// Gameplay traits are shared by behavior families; anatomy and drops remain species-specific.
const species = (id, name, model, color, options = {}) => ({
  id, name, model, color, accent: '#c9beb0', health: 20, damage: 2, speed: 1.6,
  width: .7, height: 1.25, temperament: 'passive', habitat: 'meadow', movement: 'ground',
  drops: [], xp: 2, ...options,
});
const drop = (id, min = 1, max = min, chance = 1) => ({ id, min, max, chance });
const undead = { temperament: 'hostile', habitat: 'night', burns: true, xp: 5 };
const nether = { temperament: 'hostile', habitat: 'volcanic', fireproof: true, xp: 5 };
const fish = { movement: 'swim', habitat: 'water', width: .35, height: .4, health: 6, speed: 2 };
const horse = { width: 1, height: 1.7, health: 30, speed: 3, ride: true, tame: 'apple', breed: 'golden_carrot', drops: [drop('leather', 1, 2)] };
const trader = { health: 24, trade: true, height: 1.9, speed: 1.2 };

export const MOB_LIST = [
  species('allay', 'Allay', 'fairy', '#60d9ed', { movement: 'fly', height: .7, width: .4, habitat: 'forest', collect: true, health: 20 }),
  species('armadillo', 'Armadillo', 'armadillo', '#ac826d', { health: 12, height: .65, habitat: 'desert', roll: true, brush: 'armadillo_scute', breed: 'spider_eye' }),
  species('axolotl', 'Axolotl', 'axolotl', '#efa1b8', { ...fish, health: 14, height: .5, amphibious: true, breed: 'tropical_fish', predator: true, regenerate: true }),
  species('bat', 'Bat', 'bat', '#54473e', { movement: 'fly', habitat: 'cave', health: 6, height: .5, width: .35 }),
  species('bee', 'Bee', 'bee', '#edc64b', { movement: 'fly', height: .6, width: .5, health: 10, temperament: 'neutral', poison: true, pollinate: true, breed: 'flower', drops: [] }),
  species('blaze', 'Blaze', 'blaze', '#f5b733', { ...nether, movement: 'fly', height: 1.6, ranged: 'fireball', drops: [drop('blaze_rod', 1, 2)] }),
  species('bogged', 'Bogged', 'skeleton', '#81976b', { ...undead, health: 16, ranged: 'poison_arrow', weapon: 'bow', drops: [drop('bone', 1, 2), drop('arrow', 1, 3), drop('bow', 1, 1, .08)], shear: 'mushroom' }),
  species('breeze', 'Breeze', 'breeze', '#a7babd', { temperament: 'hostile', habitat: 'cave', movement: 'hover', health: 30, height: 1.6, ranged: 'wind', speed: 3, drops: [drop('breeze_rod', 1, 2)] }),
  species('camel', 'Camel', 'camel', '#c9a061', { ...horse, health: 32, height: 2.2, habitat: 'desert', tame: null, breed: 'cactus', drops: [] }),
  species('cat', 'Cat', 'cat', '#c48a50', { habitat: 'forest', health: 10, height: .65, speed: 2.2, tame: 'cod', breed: 'salmon', repel: 'creeper', drops: [drop('string', 1, 2)] }),
  species('cave_spider', 'Cave Spider', 'spider', '#344e54', { temperament: 'hostile', habitat: 'cave', health: 12, height: .5, width: .8, poison: true, climb: true, drops: [drop('string', 1, 2), drop('spider_eye', 1, 1, .4)] }),
  species('chicken', 'Chicken', 'chicken', '#ede8df', { height: .8, width: .45, health: 4, breed: 'seeds', produce: 'egg', drops: [drop('raw_chicken'), drop('feather', 1, 2)] }),
  species('cod', 'Cod', 'fish', '#b9a781', { ...fish, drops: [drop('cod'), drop('bone_meal', 1, 1, .1)] }),
  species('cow', 'Cow', 'cow', '#655244', { health: 10, height: 1.4, width: .85, milk: true, breed: 'wheat', drops: [drop('raw_beef', 1, 3), drop('leather', 1, 2)] }),
  species('creaking', 'Creaking', 'creaking', '#706352', { temperament: 'hostile', habitat: 'pale', health: 40, height: 2.6, speed: 2.8, watched: true, damage: 4, drops: [], accent: '#ff9a31' }),
  species('creeper', 'Creeper', 'creeper', '#71a64d', { temperament: 'hostile', habitat: 'night', height: 1.65, fuse: true, drops: [drop('gunpowder', 1, 3)], xp: 5 }),
  species('dolphin', 'Dolphin', 'dolphin', '#829fa8', { ...fish, health: 10, width: .7, height: .65, speed: 3.3, grace: true, temperament: 'neutral', drops: [drop('cod')] }),
  species('donkey', 'Donkey', 'horse', '#928271', { ...horse, accent: '#c6bdae', longEars: true }),
  species('drowned', 'Drowned', 'humanoid', '#668d85', { ...undead, habitat: 'water', amphibious: true, height: 1.9, ranged: 'trident', weapon: 'trident', drops: [drop('rotten_flesh', 1, 2), drop('copper', 1, 2, .35), drop('trident', 1, 1, .12)] }),
  species('elder_guardian', 'Elder Guardian', 'guardian', '#b3ae96', { ...fish, health: 80, width: 1.5, height: 1.5, temperament: 'hostile', ranged: 'beam', damage: 6, fatigue: true, boss: true, drops: [drop('prismarine_shard', 4, 8), drop('prismarine_crystal', 2, 4), drop('sponge'), drop('cod')], xp: 50 }),
  species('ender_dragon', 'Ender Dragon', 'dragon', '#34303c', { temperament: 'hostile', habitat: 'end', movement: 'fly', width: 3.5, height: 3.5, health: 200, speed: 4, ranged: 'dragon_breath', damage: 8, boss: true, drops: [drop('dragon_egg'), drop('dragon_breath', 3, 6)], xp: 500, fireproof: true }),
  species('enderman', 'Enderman', 'enderman', '#303039', { temperament: 'neutral', habitat: 'end', height: 2.9, health: 40, speed: 3, damage: 6, teleport: true, stare: true, drops: [drop('ender_pearl', 1, 2)], accent: '#d385eb' }),
  species('endermite', 'Endermite', 'mite', '#77618a', { temperament: 'hostile', habitat: 'end', height: .35, width: .4, health: 8, drops: [] }),
  species('evoker', 'Evoker', 'illager', '#4b4a53', { temperament: 'hostile', habitat: 'forest', height: 1.9, health: 24, ranged: 'fangs', summon: 'vex', drops: [drop('totem'), drop('emerald', 1, 3)], accent: '#bb9c51' }),
  species('fox', 'Fox', 'fox', '#dc783b', { habitat: 'forest', height: .7, health: 10, speed: 2.6, breed: 'sweet_berries', predator: true, drops: [drop('sweet_berries', 1, 2)] }),
  species('frog', 'Frog', 'frog', '#b6a174', { height: .5, health: 10, amphibious: true, breed: 'slime_ball', hop: true, eatsSlime: true }),
  species('ghast', 'Ghast', 'ghast', '#e4e0dc', { ...nether, movement: 'fly', width: 2.5, height: 3, health: 10, ranged: 'fireball', damage: 6, drops: [drop('ghast_tear', 1, 2), drop('gunpowder', 1, 2)] }),
  species('glow_squid', 'Glow Squid', 'squid', '#43b7ae', { ...fish, height: 1.2, width: .8, health: 10, glow: true, drops: [drop('glow_ink_sac', 1, 3)] }),
  species('goat', 'Goat', 'goat', '#e1dacf', { habitat: 'mountain', height: 1.3, health: 10, temperament: 'neutral', ram: true, hop: true, milk: true, breed: 'wheat', brush: 'goat_horn', drops: [] }),
  species('guardian', 'Guardian', 'guardian', '#6b9990', { ...fish, health: 30, width: .85, height: .85, temperament: 'hostile', ranged: 'beam', damage: 4, drops: [drop('prismarine_shard', 1, 3), drop('prismarine_crystal', 1, 2, .5), drop('cod')] }),
  species('hoglin', 'Hoglin', 'hoglin', '#c18e7a', { ...nether, width: 1.1, height: 1.4, health: 40, damage: 5, breed: 'mushroom', ram: true, drops: [drop('raw_porkchop', 2, 4), drop('leather', 1, 2)] }),
  species('horse', 'Horse', 'horse', '#96694a', { ...horse }),
  species('husk', 'Husk', 'humanoid', '#a2936c', { ...undead, burns: false, habitat: 'desert', height: 1.9, hunger: true, drops: [drop('rotten_flesh', 1, 3), drop('iron', 1, 1, .05)] }),
  species('iron_golem', 'Iron Golem', 'golem', '#c8c8b7', { health: 100, damage: 12, height: 2.7, width: 1.3, temperament: 'guardian', defender: true, speed: 1.6, drops: [drop('iron', 3, 5), drop('flower', 1, 2)] }),
  species('llama', 'Llama', 'llama', '#c5b097', { ...horse, height: 1.9, speed: 2, tame: 'wheat', breed: 'hay', temperament: 'neutral', ranged: 'spit', damage: 1 }),
  species('magma_cube', 'Magma Cube', 'slime', '#622c24', { ...nether, health: 16, height: 1, width: 1, hop: true, split: true, drops: [drop('magma_cream', 1, 2)], accent: '#ffbf42' }),
  species('mooshroom', 'Mooshroom', 'cow', '#b74639', { health: 10, height: 1.4, width: .85, milk: true, stew: true, breed: 'wheat', shear: 'mushroom', drops: [drop('raw_beef', 1, 3), drop('leather', 1, 2)] }),
  species('mule', 'Mule', 'horse', '#796451', { ...horse, longEars: true }),
  species('ocelot', 'Ocelot', 'cat', '#cfb256', { habitat: 'forest', height: .65, health: 10, speed: 2.5, trust: 'cod', breed: 'salmon', repel: 'creeper', spots: true }),
  species('panda', 'Panda', 'bear', '#e1e0d5', { habitat: 'forest', health: 20, width: 1.1, height: 1.2, temperament: 'neutral', breed: 'bamboo', drops: [drop('bamboo', 1, 2)], accent: '#343634' }),
  species('parrot', 'Parrot', 'parrot', '#dc5743', { habitat: 'forest', movement: 'fly', height: .8, width: .35, health: 6, tame: 'seeds', drops: [drop('feather', 1, 2)], accent: '#4d98cd' }),
  species('phantom', 'Phantom', 'phantom', '#64769e', { ...undead, movement: 'fly', width: 1.2, height: .6, speed: 3.5, swoop: true, drops: [drop('phantom_membrane', 1, 2)] }),
  species('pig', 'Pig', 'pig', '#e7a19e', { health: 10, height: 1, width: .7, breed: 'carrot', ride: true, drops: [drop('raw_porkchop', 1, 3)] }),
  species('piglin', 'Piglin', 'piglin', '#c5927b', { ...nether, temperament: 'neutral', height: 1.9, health: 16, weapon: 'gold_sword', barter: true, goldAnger: true, damage: 4, drops: [drop('gold_nugget', 1, 4), drop('gold_sword', 1, 1, .1)] }),
  species('piglin_brute', 'Piglin Brute', 'piglin', '#a47c64', { ...nether, height: 1.9, health: 50, damage: 7, weapon: 'gold_axe', drops: [drop('gold_axe', 1, 1, .15)] }),
  species('pillager', 'Pillager', 'illager', '#776a61', { temperament: 'hostile', habitat: 'forest', height: 1.9, health: 24, ranged: 'arrow', weapon: 'crossbow', drops: [drop('crossbow', 1, 1, .18), drop('arrow', 1, 4)] }),
  species('polar_bear', 'Polar Bear', 'bear', '#e1e3dc', { habitat: 'snow', health: 30, width: 1.2, height: 1.4, temperament: 'neutral', damage: 6, drops: [drop('cod', 1, 3), drop('salmon', 1, 2, .5)] }),
  species('rabbit', 'Rabbit', 'rabbit', '#ae9674', { health: 3, height: .55, width: .4, hop: true, speed: 2.2, breed: 'carrot', drops: [drop('raw_rabbit'), drop('rabbit_hide'), drop('rabbit_foot', 1, 1, .15)] }),
  species('ravager', 'Ravager', 'ravager', '#797b73', { temperament: 'hostile', habitat: 'forest', health: 100, width: 1.7, height: 2.2, damage: 8, ram: true, drops: [drop('saddle')], xp: 20 }),
  species('salmon', 'Salmon', 'fish', '#bd6353', { ...fish, drops: [drop('salmon'), drop('bone_meal', 1, 1, .1)], accent: '#71997b' }),
  species('sheep', 'Sheep', 'sheep', '#dedbce', { health: 8, height: 1.2, width: .8, graze: true, shear: 'wool', breed: 'wheat', drops: [drop('raw_mutton', 1, 2), drop('wool')] }),
  species('shulker', 'Shulker', 'shulker', '#9c70a4', { temperament: 'hostile', habitat: 'end', movement: 'stationary', health: 30, height: 1, width: 1, ranged: 'shulker_bullet', drops: [drop('shulker_shell', 1, 2, .7)] }),
  species('silverfish', 'Silverfish', 'mite', '#919994', { temperament: 'hostile', habitat: 'cave', health: 8, height: .3, width: .35, speed: 2.2 }),
  species('skeleton', 'Skeleton', 'skeleton', '#cecfc5', { ...undead, height: 1.9, ranged: 'arrow', weapon: 'bow', drops: [drop('bone', 1, 3), drop('arrow', 1, 3), drop('bow', 1, 1, .1)] }),
  species('skeleton_horse', 'Skeleton Horse', 'horse', '#bfc5bb', { ...horse, health: 15, tame: null, skeletal: true, drops: [drop('bone', 1, 3)] }),
  species('slime', 'Slime', 'slime', '#7fbc64', { temperament: 'hostile', habitat: 'cave', health: 16, width: 1, height: 1, hop: true, split: true, drops: [drop('slime_ball', 1, 3)] }),
  species('sniffer', 'Sniffer', 'sniffer', '#815945', { health: 14, width: 1.3, height: 1.6, dig: true, breed: 'torchflower_seeds', accent: '#607b44' }),
  species('snow_golem', 'Snow Golem', 'snowman', '#e7eeec', { health: 4, height: 1.8, temperament: 'guardian', defender: true, ranged: 'snowball', damage: 1, drops: [drop('snowball', 2, 6)], shear: 'pumpkin' }),
  species('spider', 'Spider', 'spider', '#4e4340', { temperament: 'hostile', habitat: 'night', width: 1.2, height: .8, health: 16, climb: true, drops: [drop('string', 1, 3), drop('spider_eye', 1, 1, .4)] }),
  species('squid', 'Squid', 'squid', '#506479', { ...fish, health: 10, width: .8, height: 1.2, drops: [drop('ink_sac', 1, 3)] }),
  species('stray', 'Stray', 'skeleton', '#93a7ad', { ...undead, habitat: 'snow', height: 1.9, ranged: 'slow_arrow', weapon: 'bow', drops: [drop('bone', 1, 3), drop('arrow', 1, 3), drop('bow', 1, 1, .1)] }),
  species('strider', 'Strider', 'strider', '#ae5d59', { health: 20, habitat: 'volcanic', fireproof: true, ride: true, height: 1.7, width: .9, breed: 'mushroom', drops: [drop('string', 2, 5)] }),
  species('tadpole', 'Tadpole', 'tadpole', '#685247', { ...fish, health: 6, height: .2, width: .2, growInto: 'frog' }),
  species('trader_llama', 'Trader Llama', 'llama', '#bda080', { ...horse, height: 1.9, tame: 'wheat', breed: 'hay', temperament: 'neutral', ranged: 'spit', accent: '#377cb2' }),
  species('tropical_fish', 'Tropical Fish', 'fish', '#f6a744', { ...fish, drops: [drop('tropical_fish'), drop('bone_meal', 1, 1, .1)], accent: '#f4f1dc' }),
  species('turtle', 'Turtle', 'turtle', '#74a664', { health: 30, height: .55, width: .9, speed: .8, amphibious: true, habitat: 'beach', breed: 'seagrass', brush: 'turtle_scute', drops: [drop('seagrass', 1, 2)] }),
  species('vex', 'Vex', 'fairy', '#a1b6cf', { temperament: 'hostile', habitat: 'forest', movement: 'fly', health: 14, height: .8, width: .4, weapon: 'iron_sword', speed: 3, damage: 4, drops: [drop('iron_sword', 1, 1, .05)] }),
  species('villager', 'Villager', 'villager', '#95704c', { ...trader, drops: [] }),
  species('vindicator', 'Vindicator', 'illager', '#667675', { temperament: 'hostile', habitat: 'forest', height: 1.9, health: 24, damage: 7, weapon: 'iron_axe', drops: [drop('emerald', 1, 3), drop('iron_axe', 1, 1, .1)] }),
  species('wandering_trader', 'Wandering Trader', 'villager', '#437bae', { ...trader, drops: [], accent: '#dca645' }),
  species('warden', 'Warden', 'warden', '#315350', { temperament: 'hostile', habitat: 'cave', health: 250, height: 2.9, width: 1.4, damage: 12, speed: 2.4, ranged: 'sonic', blind: true, boss: true, drops: [drop('sculk')], xp: 100, accent: '#73d1c5' }),
  species('witch', 'Witch', 'witch', '#886b94', { temperament: 'hostile', habitat: 'forest', health: 26, height: 2.3, ranged: 'poison', regenerate: true, drops: [drop('redstone', 1, 3), drop('glowstone_dust', 1, 3), drop('sugar', 1, 3), drop('glass_bottle', 1, 2), drop('gunpowder', 1, 2)] }),
  species('wither', 'Wither', 'wither', '#42464b', { temperament: 'hostile', habitat: 'volcanic', movement: 'fly', health: 200, height: 2.5, width: 2.4, damage: 8, ranged: 'wither_skull', boss: true, regenerate: true, fireproof: true, drops: [drop('nether_star')], xp: 300 }),
  species('wither_skeleton', 'Wither Skeleton', 'skeleton', '#49494b', { ...nether, height: 2.4, damage: 5, wither: true, weapon: 'stone_sword', drops: [drop('bone', 1, 3), drop('coal', 1, 2), drop('wither_skull', 1, 1, .1), drop('stone_sword', 1, 1, .08)] }),
  species('wolf', 'Wolf', 'wolf', '#b4b6ab', { health: 20, habitat: 'forest', height: .85, width: .6, speed: 2.6, temperament: 'neutral', tame: 'bone', breed: 'raw_beef', defender: true, damage: 4 }),
  species('zoglin', 'Zoglin', 'hoglin', '#b48e7c', { ...nether, health: 40, width: 1.1, height: 1.4, damage: 5, ram: true, drops: [drop('rotten_flesh', 1, 3)], accent: '#709365' }),
  species('zombie', 'Zombie', 'humanoid', '#699562', { ...undead, height: 1.9, weapon: null, drops: [drop('rotten_flesh', 1, 3), drop('carrot', 1, 1, .1), drop('iron', 1, 1, .08)] }),
  species('zombie_horse', 'Zombie Horse', 'horse', '#78966d', { ...horse, tame: null, drops: [drop('rotten_flesh', 1, 3)] }),
  species('zombie_villager', 'Zombie Villager', 'villager', '#789065', { ...undead, height: 1.9, cure: true, drops: [drop('rotten_flesh', 1, 3)] }),
  species('zombified_piglin', 'Zombified Piglin', 'piglin', '#b29282', { ...nether, temperament: 'neutral', height: 1.9, damage: 5, weapon: 'gold_sword', groupAnger: true, drops: [drop('rotten_flesh', 1, 3), drop('gold_nugget', 1, 4), drop('gold_sword', 1, 1, .08)], accent: '#74865b' }),
];

export const MOBS = Object.freeze(Object.fromEntries(MOB_LIST.map(m => [m.id, Object.freeze(m)])));
export const TRADES = [
  { take: 'wheat', amount: 12, give: 'emerald', count: 1 },
  { take: 'coal', amount: 8, give: 'emerald', count: 1 },
  { take: 'emerald', amount: 1, give: 'bread', count: 6 },
  { take: 'emerald', amount: 2, give: 'arrow', count: 16 },
  { take: 'emerald', amount: 4, give: 'saddle', count: 1 },
  { take: 'emerald', amount: 5, give: 'iron_sword', count: 1 },
  { take: 'emerald', amount: 2, give: 'seeds', count: 8 },
  { take: 'emerald', amount: 3, give: 'healing_potion', count: 1 },
  { take: 'emerald', amount: 2, give: 'bamboo', count: 8 },
  { take: 'emerald', amount: 2, give: 'cactus', count: 4 },
];
